#!/bin/sh

system_type=$(uname -s)

# install Homebrew and a bundle of recipes
if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
  echo "Updating homebrew packages"
  brew upgrade
  echo "Cleaning homebrew cache"
  brew cleanup -s

  # Copy fonts to ~/Library/Fonts
  echo "Copying fonts to user folder"
  # uri generated on Dropbox website using 'copy share link' button for target folder, then change dl param to 1.
  curl -L "https://www.dropbox.com/sh/tmwgqdh7yh4nr61/AAC4CzYolyMUwN_RY209Lhjda?dl=1" --output ~/Downloads/yadm-extra-fonts.zip
  # only copy newer files and overwrite. q will copy quietly (qq for very quiet). Specify target directory with d. -x / should suppress warnings during unzip, see https://stackoverflow.com/questions/21322416/unzip-warning-and-mapname for more info.
  unzip -quo ~/Downloads/yadm-extra-fonts.zip -x / -d ~/Library/Fonts/
  rm ~/Downloads/yadm-extra-fonts.zip

    # Copy fonts to ~/Library/Services
  echo "Copying Services to user folder"
  # uri generated on Dropbox website using 'copy share link' button for target folder, then change dl param to 1.
  curl -L "https://www.dropbox.com/sh/imjnxu278nmrn18/AADQ7pp4XycdP7igy0ARa0R2a?dl=1" --output ~/Downloads/yadm-extra-services.zip
  # only copy newer files and overwrite. q will copy quietly (qq for very quiet). Specify target directory with d. -x / should suppress warnings during unzip, see https://stackoverflow.com/questions/21322416/unzip-warning-and-mapname for more info.
  unzip -quo ~/Downloads/yadm-extra-services.zip -x / -d ~/Library/Services/
  rm ~/Downloads/yadm-extra-services.zip

fi

# install Vim plugins
if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
