#!/bin/sh

system_type=$(uname -s)

# install Homebrew and a bundle of recipes
if [ "$system_type" = "Darwin" ]; then
  # Copy fonts to ~/Library/Fonts
  echo "Copying fonts to user folder"
  # uri generated on Dropbox website using 'copy share link' button for target folder, then change dl param to 1.
  curl --http1.1 -sL "https://www.dropbox.com/sh/tmwgqdh7yh4nr61/AAC4CzYolyMUwN_RY209Lhjda?dl=1" --output ~/Downloads/yadm-extra-fonts.zip
  # only copy newer files and overwrite. q will copy quietly (qq for very quiet). Specify target directory with d. -x / should suppress warnings during unzip, see https://stackoverflow.com/questions/21322416/unzip-warning-and-mapname for more info.
  unzip -quo ~/Downloads/yadm-extra-fonts.zip -x / -d ~/Library/Fonts/
  rm ~/Downloads/yadm-extra-fonts.zip

    # Copy fonts to ~/Library/Services
  echo "Copying Services to user folder"
  # uri generated on Dropbox website using 'copy share link' button for target folder, then change dl param to 1.
  curl --http1.1 -sL "https://www.dropbox.com/sh/imjnxu278nmrn18/AADQ7pp4XycdP7igy0ARa0R2a?dl=1" --output ~/Downloads/yadm-extra-services.zip
  # only copy newer files and overwrite. q will copy quietly (qq for very quiet). Specify target directory with d. -x / should suppress warnings during unzip, see https://stackoverflow.com/questions/21322416/unzip-warning-and-mapname for more info.
  unzip -quo ~/Downloads/yadm-extra-services.zip -x / -d ~/Library/Services/
  rm ~/Downloads/yadm-extra-services.zip

fi

# install Vim plugins
if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

# install zplug from source
if [ ! -d "$HOME/.zplug" ]; then
  echo "Installing Zplug"
  export ZPLUG_HOME=$HOME/.zplug
  mkdir -p $ZPLUG_HOME
  git clone -q https://github.com/zplug/zplug $ZPLUG_HOME
  #source $ZPLUG_HOME/init.zsh
  source $HOME/.zshrc
  zplug install
fi


# Make all executable files (excluding templates and editor backups) in the
# ~/.config/yadm/bootstrap.d directory when run.
# See https://raw.githubusercontent.com/TheLocehiliosan/yadm/master/contrib/bootstrap/bootstrap-in-dir for more info.

set -eu

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

if [[ ! -d "$BOOTSTRAP_D" ]]; then
    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
    exit 1
fi

find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
        if ! "$bootstrap"; then
            echo "Error: bootstrap '$bootstrap' failed" >&2
            exit 1
        fi
    fi
done